---
- name: Install Tools and Deploy Kubernetes Application
  become: true
  hosts: your_k8s_hosts

  tasks:
    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Install kubectl
      command: 'curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl'

    - name: Install Helm
      command: 'curl -o /tmp/helm.tar.gz -LO https://get.helm.sh/helm-v3.10.1-linux-amd64.tar.gz && tar -C /tmp/ -zxvf /tmp/helm.tar.gz && mv /tmp/linux-amd64/helm /usr/local/bin/helm && chmod +x /usr/local/bin/helm'

    - name: Install Nginx Ingress Controller
      command: 'helm template ingress-nginx ingress-nginx --repo https://kubernetes.github.io/ingress-nginx --version {{ 4.9.0 }} --namespace ingress-nginx > {{ playbook_dir }}/kubernetes/ingress/controller/nginx/manifests/nginx-ingress.{{ v1.9.5 }}.yaml'

    - name: Deploy "Hello World" Application
      k8s:
        definition: '{{ playbook_dir }}/k8s-manifests/hello-world.yaml'

    - name: Create TLS Secret
      command: 'kubectl create secret tls hello-world-tls-secret --cert={{ playbook_dir }}/certs/tls.crt --key={{ playbook_dir }}/certs/tls.key'

    - name: Deploy Ingress with TLS
      k8s:
        definition: '{{ playbook_dir }}/k8s-manifests/ingress.yaml'